# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'fdlsandbox' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for fdlsandbox

  pod 'Firebase/Analytics'
  pod 'Firebase/DynamicLinks'

  target 'fdlsandboxTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'fdlsandboxUITests' do
    # Pods for testing
  end

end
